if(typeof ebaysc==="undefined")var ebaysc={rokenCalled:false};
var ebayShare={element:null,plusOneButton:null,plusOneNoCountButton:null,etafScript:"http://ir.ebaystatic.com/z/y4/euatbhbxa22ezbxbs5rxdnswf.js",nonEtafScript:"http://ir.ebaystatic.com/z/eq/2vfbtv4k5m1ldf2yttpd0d44r.js",signInDuration:120,hasEtafParam:0,hasEtafToEmail:false,etafLanguage:"en_US",etafTitle:"",emailBody:"",emailSubject:"",params:null,usesEtaf:0,url:"",cssLoaded:false,cssStack:[],test:"",scriptsLoaded:[],language:"",imageUrl:"",spid:"",spriteUrl:"http://p.ebaystatic.com/aw/pics/social/spr_share_widget_ds3_optimized.png",
shareCmdHost:"",title:"",sharedObjects:{item:"ITEM",product:"PRODUCT"},strings:{en_US:{share:"Share:",tt_email:"Email to friends",tt_facebook:"Share on Facebook - opens in a new window or tab",tt_twitter:"Share on Twitter - opens in a new window or tab",tt_pinterest:"Share on Pinterest - opens in a new window or tab",tweet:"Look what I found on @eBay!"},de_DE:{share:"Teilen:",tt_email:"E-Mail an Freunde senden",tt_facebook:"Auf Facebook teilen - wird in einem neuen Fenster oder Reiter ge\u00f6ffnet",
tt_twitter:"Auf Twitter teilen - wird in einem neuen Fenster oder Reiter ge\u00f6ffnet",tt_pinterest:"Auf Pinterest teilen - wird in einem neuen Fenster oder Reiter ge\u00f6ffnet",tweet:"Das habe ich bei @eBay gefunden"},it_IT:{share:"Condividi:",tt_email:"Condividilo per email - si apre in una nuova finestra o scheda",tt_facebook:"Condividilo su Facebook - si apre in una nuova finestra o scheda",tt_twitter:"Condividilo su Twitter - si apre in una nuova finestra o scheda",tt_pinterest:"Condividilo su Pinterest - si apre in una nuova finestra o scheda",
tweet:"L'ho trovato su #eBay!"},fr_FR:{share:"Partager:",tt_email:"Envoyer par e-mail \u00e0 un ami\u00a0\u2013 s'ouvre dans une autre fen\u00eatre ou un autre onglet",tt_facebook:"Partager sur Facebook\u00a0\u2013 s'ouvre dans une autre fen\u00eatre ou un autre onglet",tt_twitter:"Partager sur Twitter\u00a0\u2013 s'ouvre dans une autre fen\u00eatre ou un autre onglet",tt_pinterest:"Partager sur Pinterest\u00a0\u2013 s'ouvre dans une autre fen\u00eatre ou un autre onglet",tweet:"Ma trouvaille sur @eBay !"},
ca_FR:{share:"Partager:",tt_email:"Envoyer par courriel",tt_facebook:"Partager sur Facebook - s'ouvre dans une autre fen\u00eatre ou un autre onglet",tt_twitter:"Partager sur Twitter - s'ouvre dans une autre fen\u00eatre ou un autre onglet",tt_pinterest:"Partager sur Pinterest - s'ouvre dans une autre fen\u00eatre ou un autre onglet",tweet:"Ma belle trouvaille sur @eBay!"},es_ES:{share:"Compartir:",tt_email:"Enviar por correo - se abre en una ventana o pesta\u00f1a nueva",tt_facebook:"Compartir en Facebook - se abre en una ventana o pesta\u00f1a nueva",
tt_twitter:"Compartir en Twitter - se abre en una ventana o pesta\u00f1a nueva",tt_pinterest:"Compartir en Pinterest - se abre en una ventana o pesta\u00f1a nueva",tweet:"Mira lo que hay en @eBay:"},nl_BE:{share:"Delen:",tt_email:"E-mailen naar vrienden",tt_facebook:"Delen op Facebook - wordt geopend in een nieuw venster of op een nieuw tabblad",tt_twitter:"Delen op Twitter - wordt geopend in een nieuw venster of op een nieuw tabblad",tt_pinterest:"Delen op Pinterest - wordt geopend in een nieuw venster of op een nieuw tabblad",
tweet:"Dit heb ik gevonden op @eBay"},nl_NL:{share:"Delen:",tt_email:"E-mailen naar vrienden",tt_facebook:"Delen op Facebook - wordt in een nieuw venster of tabblad geopend",tt_twitter:"Delen op Twitter - wordt in een nieuw venster of tabblad geopend",tt_pinterest:"Delen op Pinterest - wordt in een nieuw venster of tabblad geopend",tweet:"Dit heb ik op @eBay gevonden"},pl_PL:{share:"Udost&#281;pnij:",tt_email:"Powiadom znajomych",tt_facebook:"Udost&#281;pnij na Facebooku - otwiera si&#281; w nowym oknie lub zak&#322;adce",
tt_twitter:"Pole&#263; na Twitterze - otwiera si&#281; w nowym oknie lub zak&#322;adce",tt_pinterest:"Opublikuj na Pinterest - otwiera si&#281; w nowym oknie lub zak&#322;adce",tweet:"Zobacz, co znalaz&#322;em(&#322;am) na @eBay"},ru_RU:{share:"\u041f\u043e\u0434\u0435\u043b\u0438\u0442\u044c\u0441\u044f \u0441 \u0434\u0440\u0443\u0437\u044c\u044f\u043c\u0438:",tt_email:"\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 \u0434\u0440\u0443\u0437\u044c\u044f\u043c",
tt_facebook:"\u041f\u043e\u0434\u0435\u043b\u0438\u0442\u044c\u0441\u044f \u0432 Facebook - \u043e\u0442\u043a\u0440\u043e\u0435\u0442\u0441\u044f \u043d\u043e\u0432\u043e\u0435 \u043e\u043a\u043d\u043e \u0438\u043b\u0438 \u0432\u043a\u043b\u0430\u0434\u043a\u0430",tt_twitter:"\u041f\u043e\u0434\u0435\u043b\u0438\u0442\u044c\u0441\u044f \u0432 Twitter - \u043e\u0442\u043a\u0440\u043e\u0435\u0442\u0441\u044f \u043d\u043e\u0432\u043e\u0435 \u043e\u043a\u043d\u043e \u0438\u043b\u0438 \u0432\u043a\u043b\u0430\u0434\u043a\u0430",
tt_pinterest:"\u041f\u043e\u0434\u0435\u043b\u0438\u0442\u044c\u0441\u044f \u0432 Pinterest - \u043e\u0442\u043a\u0440\u043e\u0435\u0442\u0441\u044f \u043d\u043e\u0432\u043e\u0435 \u043e\u043a\u043d\u043e \u0438\u043b\u0438 \u0432\u043a\u043b\u0430\u0434\u043a\u0430",tweet:"\u0412\u043e\u0442 \u0447\u0442\u043e \u043c\u043d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u043d\u0430\u0439\u0442\u0438 \u043d\u0430 @eBay"}},pageId:{sip:2047465,sip_mobile:2047978,vi_raptor:2047675,vi_v3:4340,vi_mobile:5408,
vi_signals_widget:2053605},createScript:function(a){for(var c=false,b=0;b<ebayShare.scriptsLoaded.length;b++)if(ebayShare.scriptsLoaded[b]==a){c=true;break}if(!c){var d=document.createElement("script");d.type="text/javascript";d.async=true;d.src=a;document.getElementsByTagName("head")[0].appendChild(d);ebayShare.scriptsLoaded.push(a)}},getElementsByClass:function(a){var c=[],b=document.getElementsByTagName("*"),d=b.length,e=RegExp("(^|\\s)"+a+"(\\s|$)"),f,g,j=[];for(g=f=0;f<d;f++)if(e.test(b[f].className)){j[g]=
b[f];g++}return j},attr:function(a){var c=this.element.getAttribute(a);if(c)return c},html:function(a){if(a||a===0||a===""){this.element.innerHTML=a;return this}else return this.element.innerHTML},removeArrayElement:function(a,c,b){a.splice(c,(b||c||1)+(c<0?a.length:0));return a.length},parseUrlParams:function(){for(var a={},c=document.location.search.substring(1),b=c.split("&"),d=0;d<b.length;d++){var e=b[d].split("=");a[e[0]]=e[1]}return a},loadScript:function(a,c){var b=document.createElement("script");
b.id=a;b.src=c;document.getElementsByTagName("head")[0].appendChild(b)},launchEtaf:function(a,c){ebayShare.params=ebayShare.parseUrlParams();if(ebayShare.params.etafElem!==undefined){var b=ebayShare.params.etafElem;c=document.getElementById(b)}if(c!==undefined&&c!==null){ebayShare.url=c.getAttribute("etafShareUrl");ebayShare.etafTitle=c.getAttribute("etafShareTitle");ebayShare.clickedEtafElement=c.getAttribute("id")}document.getElementById("ebay-etaf")?etaf.showEmailFlow():ebayShare.loadScript("ebay-etaf",
a)},checkEtafParam:function(){ebayShare.params=ebayShare.parseUrlParams();if(ebayShare.params.etaf!==undefined&&ebayShare.params.etaf=="1"){if(Math.round((new Date).getTime()/1E3)-parseInt(ebayShare.params.tp,10)<ebayShare.signInDuration)ebayShare.hasEtafParam=1;if(ebayShare.params.email!==undefined)ebayShare.hasEtafToEmail=true}},init:function(){var a=ebayShare.getElementsByClass("eb:share"),c=0;ebayShare.shareCmdHost=ebayShare.getShareCommandHost(window.location.href);for(var b=0;b<a.length;b++){c++;
ebayShare.render(a[b],c);ebayShare.renderPlusOne("count");ebayShare.renderPlusOne("noCount")}if(ebaysc.rokenCalled===false){var d=ebayShare.parseUrlParams();if(d.roken){var e=document.createElement("img");e.setAttribute("src","http://r.ebay.com/"+d.roken);e.setAttribute("width","1");e.setAttribute("height","1");e.setAttribute("align","left");var f=document.getElementById("ebayShare_1");f.appendChild(e);ebaysc.rokenCalled=true}}},getEnv:function(a){var c=a.replace(/http:\/\//,"").split("/");return c[0].indexOf(".qa.ebay.")!=
-1?"QA":c[0].indexOf("corp.ebay.")!=-1?"DEV":c[0].indexOf("dev.ebay.")!=-1?"DEV":c[0].indexOf("ebay.")!=-1?"PROD":"OON"},getShareCommandHost:function(a){var c="",b=null,d=a.replace(/http:\/\//,"").split("/");b=d[0].split(".");b.splice(0,1);b=b.join(".");return c=ebayShare.getEnv(a)==="QA"?b.indexOf("stratus")!==-1?"www."+b.match(/qa\.ebay\.[a-zA-Z]+\.*[a-zA-Z]*/g):"www."+b.match(/([a-zA-Z]+\.[a-zA-Z]+\.)*qa\.ebay\.[a-zA-Z]+\.*[a-zA-Z]*/g):ebayShare.getEnv(a)==="PROD"?b.indexOf("stratus")!==-1?"www."+
b.match(/ebay\.[a-zA-Z]+\.*[a-zA-Z]*/g):"www."+b.match(/[a-zA-Z]*\.*[a-zA-Z]*\.*ebay\.[a-zA-Z]+\.*[a-zA-Z]*/g):ebayShare.getEnv(a)==="DEV"?"www.qa."+d[0].match(/ebay\.[a-zA-Z]+\.*[a-zA-Z]*/g):"www.ebay.com"},renderPlusOne:function(a){var c;c=a=="count"?"scSharePlusOne":"scSharePlusOneNoCount";if(ebayShare.getElementsByClass(c)!==null)for(var b=ebayShare.getElementsByClass(c),d=0;d<b.length;d++){var e=b[d];a=="count"?e.appendChild(ebayShare.plusOneButton):e.appendChild(ebayShare.plusOneNoCountButton)}},
getCustomAttr:function(a){return ebayShare.attr("data-"+a)?ebayShare.attr("data-"+a):ebayShare.language in ebayShare.strings?ebayShare.strings[ebayShare.language][a]:ebayShare.strings.en_US[a]},isIE:function(){var a=navigator.appName=="Microsoft Internet Explorer"?true:false;return a},isFF:function(){var a=navigator.userAgent.indexOf("Firefox")!=-1?true:false;return a},isWin:function(){return navigator.appVersion.indexOf("Windows")!=-1?true:false},isMac:function(){return navigator.appVersion.indexOf("Mac")!=
-1?true:false},removeClass:function(a){var c=this.element.className,b=RegExp("(\\s|^)"+a+"(\\s|$)");if(c.match(b))this.element.className=this.element.className.replace(b,"")},render:function(a,c){this.element=a;var b=ebayShare.attr("data-destinations"),d=ebayShare.attr("data-language")?ebayShare.attr("data-language"):"en_US",e=ebayShare.attr("data-style"),f=ebayShare.attr("data-url"),g=ebayShare.attr("data-title");ebayShare.emailSubject=ebayShare.attr("data-email_subject");ebayShare.emailBody=ebayShare.attr("data-email_body");
ebayShare.spid=parseInt(ebayShare.attr("data-spid"),10);ebayShare.imageUrl="";ebayShare.language=d==="de_CH"||d==="de_AT"?ebayShare.etafLanguage="de_DE":d==="fr_BE"?ebayShare.etafLanguage="fr_FR":ebayShare.etafLanguage=ebayShare.strings.hasOwnProperty(d)?d:"en_US";var j=ebayShare.getCustomAttr("share");ebayShare.usesEtaf=1;ebayShare.checkEtafParam();ebayShare.title=g?g:ebayShare.getPageTitle();b=b?b=b.split(","):b=["email"];if(f){ebayShare.removeClass("eb:share");e=e?e:"simple";var i=".scShareIcon {width:16px;height:20px;background:url('"+
ebayShare.spriteUrl+"');float:left;cursor:pointer;font-size:20px;overflow:hidden;padding-right:7px;text-decoration:none !important;}.scShareText {font:13px arial,verdana;color:black;height:19px;float:left;padding-right:3px;}.scShareTextDropDown {font:13px arial,verdana;color: #002398;height:19px;float:left;padding-right:6px;}.scSharePointer {cursor:pointer;}.scShare_facebook {background-position: 0px -22px;}.scShare_twitter {background-position: 0px -43px;}.scShare_email {background-position: 0px -1px;}.scShare_pinterest {background-position: 0px -85px;}.scShareFbLike {width:65px;height:21px;float:left;padding-right: 10px;padding-left:3px;position:relative;top:-2px;}.scSharePlusOne {width:49px;height:21px;float:left;padding-right:3px;padding-left:3px;position:relative;top:1px;}.scSharePlusOneNoCount {overflow:hidden;width:23px;height:21px;float:left;padding-left:3px;padding-right:5px;position:relative;top:1px;}.scShare7 {width: 2px;float:left;}.scShare {float: left; position:relative;}",
k=navigator.appVersion.indexOf("Mac")!=-1?k=45:k=43;i+=".scShareFbLikeNoCount {overflow:hidden;width:"+k+"px;height:21px;float:left;padding-right:7px;padding-left:3px;position:relative;top:-2px;}";ebayShare.loadCss(i,"baseCSS");var o,s=0,m="",l,h,n,p="";switch(e){case "mobile":case "simple":l='<div id="ebayShare_'+c+'"><div class="scShareText">'+j+"</div>";for(i=0;i<b.length;i++){h=ebayShare.sanitizeDestination(b[i]);switch(h){case "fbLike":case "fbLikeNoCount":case "plusOne":case "plusOneNoCount":p+=
ebayShare.addSideButtons(h);break;case "email":case "facebook":case "twitter":case "pinterest":if(h=="pinterest")if(ebayShare.getImageUrl())h="pinterest";else break;m=ebayShare.getCustomAttr("tt_"+h);n=ebayShare.getShareUrl(h,ebayShare.language,f);var q="",r="";if(h=="email")if(ebayShare.usesEtaf===1){onclickEvt=ebayShare.isItemPage("vi")?"ebayShare.launchEtaf(ebayShare.etafScript,this)":"ebayShare.launchEtaf(ebayShare.nonEtafScript,this)";r=ebayShare.title.replace('"',"'");l+='<a id="scShare_emailId'+
c+'"  href="javascript:void(0);" etafShareUrl="'+f+'" etafShareTitle="'+r+'" onclick="'+onclickEvt+'" title="'+m+'" class="scShareIcon scShare_'+h+'" data-destination="'+h+'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>'}else{q=ebayShare.isItemPage("vi")?' target="_blank"':ebayShare.isWin()?' target="_blank"':"";l+='<a href="'+n+'" title="'+m+'" class="scShareIcon scShare_'+h+'" data-destination="'+h+'"'+q+">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>"}else l+='<a href="'+n+'" title="'+m+'" class="scShareIcon scShare_'+
h+'" data-destination="'+h+'" target="_blank">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>'}}l+=p+"</div>";ebayShare.html(l);ebayShare.hasEtafParam===1&&ebayShare.launchEtaf(ebayShare.etafScript)}}},getWidgetStyle:function(){var a=ebayShare.attr("data-style")?ebayShare.attr("data-style"):"simple";return a},getImageUrl:function(){var a=ebayShare.attr("data-imageUrl");if(ebayShare.imageUrl)return ebayShare.imageUrl;if(a)return ebayShare.imageUrl=a;else{var c=ebayShare.getOGInfo("og:image");if(!c)return false;
ebayShare.imageUrl=ebayShare.imageUrlCleanUp(c);return c}},getOGInfo:function(a){for(var c=document.getElementsByTagName("meta"),b=0;b<c.length;b++)if(typeof c[b]=="object"&&c[b].getAttribute("property")===a)return c[b].content},imageUrlCleanUp:function(a){if(a.indexOf("+")>-1)a=a.replace(RegExp("\\+","g"),"%2B");return a},sanitizeDestination:function(a){return a.replace(/\s*/g,"")},capitalize:function(a){return a.substr(0,1).toUpperCase()+a.substr(1)},addSideButtons:function(a){var c="";switch(a){case "fbLike":c+=
ebayShare.addFbLike(true);break;case "fbLikeNoCount":c+=ebayShare.addFbLike(false);break;case "plusOne":c+=ebayShare.addPlusOne(true);break;case "plusOneNoCount":c+=ebayShare.addPlusOne(false)}return c},addFbLike:function(a){var c=ebayShare.getOGInfo("og:url");if(c===null||c===undefined)c=window.location;var b,d='<iframe scrolling="no" frameborder="0" src="http://www.facebook.com/plugins/like.php?href='+c+'&amp;send=false&amp;layout=button_count&amp;width=50&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21&amp;appId=102628213125203" allowtransparency="true"></iframe>';
b=a?"scShareFbLike":"scShareFbLikeNoCount";return'<div class="'+b+'">'+d+"</div>"},addPlusOne:function(a){var c=document.createElement("g:plusone"),b;c.setAttribute("size","small");if(a){c.setAttribute("count","true");ebayShare.plusOneButton=c;b='<div class="scSharePlusOne"></div>'}else{c.setAttribute("count","false");ebayShare.plusOneNoCountButton=c;b='<div class="scSharePlusOneNoCount"></div>'}ebayShare.createScript("https://apis.google.com/js/plusone.js");return b},loadCss:function(a,c){for(var b=
0;b<ebayShare.cssStack.length;b++)if(ebayShare.cssStack[b]==c)return;ebayShare.cssStack.push(c);var d=document.createElement("style");d.setAttribute("type","text/css");document.getElementsByTagName("head")[0].appendChild(d);var e=document.createTextNode(a);if(d.styleSheet)d.styleSheet.cssText=e.nodeValue;else d.appendChild(e)},getPageTitle:function(){for(var a=document.getElementsByTagName("meta"),c=false,b,d=0;d<a.length;d++)if(typeof a[d]=="object"&&a[d].getAttribute("property")=="og:title"){b=
a[d].content;c=true;break}if(!c)b=document.title;return b=this.sanitizeTitle(b)},sanitizeTitle:function(a){return a.replace(/'/g,"%27")},getItemId:function(a){var c=0,b=/http:\/\/[^\/]+\.ebay\.[^\/]+\/(soc\/)?itm\//,d=/http:\/\/[^\/]+\.ebay\.[^\/]+\/ws\/eBayISAPI.dll\?ViewItem&item=(\d+)/,e;if(b.test(a)){e=a.split("/");c=e[e.length-1].split("?")[0]}else if(d.test(a)){var f=a.match(d);c=f[1]}else{e=a.split("/");c=e[e.length-1].split("?")[0]}if(!isNaN(parseInt(c,10)))return parseInt(c,10);return 0},
isItemPage:function(a){switch(a){case "si":if(ebayShare.spid===ebayShare.pageId.sip||ebayShare.spid===ebayShare.pageId.sip_mobile)return true;break;default:if(ebayShare.spid===ebayShare.pageId.vi_v3||ebayShare.spid===ebayShare.pageId.vi_raptor||ebayShare.spid===ebayShare.pageId.vi_mobile||ebayShare.spid===ebayShare.pageId.vi_signals_widget)return true}return false},getSharedType:function(){return ebayShare.attr("data-shared_type")},getFacebookShareUrl:function(a,c,b){var d="",e="",f="/soc/share";
if(ebayShare.isItemPage("vi")||ebayShare.isItemPage("si")||ebayShare.getSharedType()===ebayShare.sharedObjects.item){language=ebayShare.attr("data-language");switch(language){case "en_US":shareUrl=ebayShare.getEnv(b)==="QA"||ebayShare.getEnv(b)==="DEV"?"http://www.qa.ebay.com/soc/itm/"+c:"http://www.ebay.com/soc/itm/"+c;break;default:shareUrl=encodeURIComponent(b)}}else shareUrl=encodeURIComponent(b);var g=encodeURIComponent(ebayShare.title);if(a==18){var j=etaf.fbSendappidProd;if(ebayShare.getEnv(b)===
"QA"||ebayShare.getEnv(b)==="DEV"){j=etaf.fbSendappidQa;g=g+"   ::::::::::    "+shareUrl;shareUrl="http://www.ebay.com"}e="&apnd="+encodeURIComponent("app_id="+j+"&display=popup")}d="http://"+ebayShare.shareCmdHost+f+"?swd="+a+"&du="+shareUrl+"&rt=nc&t="+g+"&spid="+ebayShare.spid+e;if(ebayShare.isItemPage("vi")||ebayShare.isItemPage("si"))d+="&shorten=0";return d},getShareUrl:function(a,c,b){var d=-1,e,f,g="/soc/share";if(ebayShare.isItemPage("vi")||ebayShare.isItemPage("si")||ebayShare.getSharedType()===
ebayShare.sharedObjects.item)d=ebayShare.getItemId(b);switch(a){case "email":if(ebayShare.isItemPage("vi")&&ebayShare.getWidgetStyle()!=="mobile"){var j=window.location.host.replace("www","contact");return"http://"+j+"/ws1/ebayISAPI.dll?ShowEmailAuctionToFriend&rt=nc&item="+d}else{e=encodeURIComponent(b);f="http://"+ebayShare.shareCmdHost+g+"?swd=13&du="+e+"&rt=nc&t="+encodeURIComponent(ebayShare.getCustomAttr("email_body"))+"&spid="+ebayShare.spid+"&subject="+encodeURIComponent(ebayShare.getCustomAttr("email_subject"))}break;
case "facebook":f=ebayShare.getFacebookShareUrl(2,d,b);break;case "twitter":var i=ebayShare.title,k=ebayShare.getCustomAttr("tweet");if(i.length>50)i=i.substring(0,50);var o=ebayShare.getLangForThirdParty("twitter",c);k=ebayShare.attr("data-tweet")!==null?encodeURIComponent(k):encodeURIComponent(k+" "+i);e=encodeURIComponent(b);f="http://"+ebayShare.shareCmdHost+g+"?swd=3&du="+e+"&rt=nc&t="+k+"&spid="+ebayShare.spid+"&lang="+o;break;case "pinterest":e=encodeURIComponent(b);f="http://"+ebayShare.shareCmdHost+
g+"?swd=11&du="+e+"&rt=nc&t="+encodeURIComponent(i)+"&spid="+ebayShare.spid+"&media="+ebayShare.imageUrl}if(d!==-1)f+="&itm="+d;return f},getLangForThirdParty:function(a,c){var b="";if(a==="twitter")b=this.getLangForTwitter(c);return b},getLangForTwitter:function(a){switch(a){case "fr_FR":case "be_FR":lang="fr";break;case "de_DE":case "de_CH":case "de_AT":lang="de";break;case "it_IT":lang="it";break;case "nl_NL":case "nl_BE":lang="nl";break;case "pl_PL":lang="pl";break;case "es_ES":lang="es";break;
case "ru_RU":lang="ru";break;default:lang="en"}return lang},swapUrl:function(a){var c=ebayShare.getElementsByClass("scShareIcon"),b=0,d,e,f=c.length;for(b=0;b<f;b++){e=ebayShare.sanitizeDestination(c[b].getAttribute("data-destination"));if(e==="email"){c[b].setAttribute("etafshareurl",a.url);c[b].setAttribute("etafsharetitle",a.title)}else{d=c[b].getAttribute("href");if(e==="pinterest")d=d.replace(/media=[^&]*&/i,"media="+a.imageUrl+"&");d=d.replace(/du=[^&]*&/i,"du="+a.url+"&");c[b].setAttribute("href",
d)}}}};ebayShare.init();
