
vjo.ctype("vjo.darwin.core.button.Button").needs("vjo.dsf.Element","E").needs("vjo.dsf.Message","M").needs("vjo.dsf.ServiceEngine","S").needs("vjo.dsf.client.Browser").needs("vjo.dsf.EventDispatcher","ED").protos({m:null,state:null,dCls:null,O:null,constructs:function(m){var t=this;t.m=m;t.state="";var Sc=m.scope;t.dCls=Sc+"-b "+"moz "+Sc+"-b";t.Cls=[{"mouseup":[0,""],"mousedown":[0,"p"],"mouseout":[0,""],"mouseover":[0,"o"],"focus":[1,"o"],"blur":[1,""],"entrue":"d","enfalse":""}];t.O=[];t.init();},init:function(){var t=this,D=t.vj$.ED,O=t.get();D.addEventListener(window,"load",function(){t.enDis(t.m.dis);},window);for(var i in t.Cls[0]){var V=O[t.Cls[0][i][0]];if(V){D.addEventListener(V,i,t.handler(i),t);}}},handler:function(eT){var t=this;return function(){t.changeState({"eventType":eT});};},get:function(){var t=this,E=t.vj$.E,m=t.m;if(t.O.length==0){t.O.push(E.get(m.SId),E.get(m.BId),E.get(m.LId));}
return t.O;},changeState:function(e){var t=this,O=t.get(),eT=e.eventType;if((O[1].disabled||O[0].className.indexOf("-bd")!=-1)||(t.state=="mousedown"&&eT=="focus")){return;}
t.state=eT;O[0].className=t.dCls+t.Cls[0][eT][1]+" "+t.m.BT;},enable:function(){this.enDis(false);},disable:function(){this.enDis(true);},isDisabled:function(){return this.m.dis;},enDis:function(_c){var t=this,N="none",E=t.vj$.E,m=t.m,O=t.get(),b=O[1],bS=b.style,tS=(O[2])?O[2].style:"",B=vjo.dsf.client.Browser.bIE;O[0].className=t.dCls+t.Cls[0]["en"+_c]+" "+t.m.BT;t.m.dis=_c;if(m.tp!==2){b.disabled=_c;}else{b.display=(_c)?N:"";}
if(!B&&m.tp!=2){return;}
if(_c){tS.display="inline-block";if(!B){tS.display="-moz-inline-box";b.style.setProperty("display","none","important");}
bS.display=N;}else{tS.display=N;bS.display="";}}}).props({enable:function(_e){var o=vjo.Registry.get(_e);if(o){o.enable();}},disable:function(ins){var o=vjo.Registry.get(ins);if(o){o.disable();}},onSubmit:function(_12,evt,_14){this.sendMessage(_12,evt);return(!_14&&_14==false)?false:true;},sendMessage:function(_15,evt){var o=this.vj$,msg=new o.M(_15);msg.event=evt;o.S.handleRequest(msg);}}).endType();

vjo.ctype("vjo.com.ebay.darwin.app.signin.SignOutConfirm").needs("vjo.dsf.Element").props({ebayExitRecovery:function(_1,_2,_3){var _4=document.getElementById(_2);var _5=document.getElementById(_3);if(_1){_4.style.display="block";_5.style.display="none";}else{_4.style.display="none";_5.style.display="block";}},ebayExitRecoveryShowBackup:function(_6,_7){var _8=document.getElementById(_7);if(!_6){_8.style.display="block";}},BeforeLoadMethods:function(){var _9=document.body.clientWidth;if(_9>=1250){document.body.className=document.body.className+" sz1200";}}}).endType();
